"""Initial migration

Revision ID: 7cbafdf673da
Revises: 
Create Date: 2025-03-27 09:38:55.473899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cbafdf673da'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DeTaiNCKHGV',
    sa.Column('ma_de_tai', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ten_de_tai', sa.String(length=255), nullable=False),
    sa.Column('tg_bat_dau', sa.DateTime(), nullable=False),
    sa.Column('tg_nghiem_thu', sa.DateTime(), nullable=False),
    sa.Column('tg_thuc_nghiem', sa.DateTime(), nullable=False),
    sa.Column('trang_thai', sa.Integer(), nullable=False),
    sa.Column('tien_do', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ma_de_tai')
    )
    op.create_table('DeTaiNCKHSV',
    sa.Column('ma_de_tai', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ten_de_tai', sa.String(length=255), nullable=False),
    sa.Column('dot_thuc_hien', sa.Integer(), nullable=False),
    sa.Column('trang_thai', sa.Integer(), nullable=False),
    sa.Column('tien_do', sa.Integer(), nullable=False),
    sa.Column('diem_so', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('ma_de_tai')
    )
    op.create_table('HoiDongTruong',
    sa.Column('ma_hd', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('so_hd', sa.Integer(), nullable=True),
    sa.Column('loai_hd', sa.Integer(), nullable=False),
    sa.Column('ngay_bao_cao', sa.Date(), nullable=True),
    sa.Column('dia_diem', sa.Text(), nullable=True),
    sa.Column('trang_thai', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('ma_hd')
    )
    op.create_table('HuongNghienCuu',
    sa.Column('ma_hnc', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ten_hnc', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('ma_hnc')
    )
    op.create_table('KhenThuong',
    sa.Column('ma_khen_thuong', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('cap_do', sa.Integer(), nullable=False),
    sa.Column('muc_do', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ma_khen_thuong')
    )
    op.create_table('Khoa',
    sa.Column('ma_khoa', sa.String(length=20), nullable=False),
    sa.Column('ten_khoa', sa.String(length=255), nullable=False),
    sa.Column('dia_chi', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('ma_khoa')
    )
    op.create_table('TaiKhoan',
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('mat_khau', sa.String(length=255), nullable=False),
    sa.Column('quyen_han', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('GiangVien',
    sa.Column('ma_gv', sa.String(length=20), nullable=False),
    sa.Column('ten_gv', sa.String(length=255), nullable=False),
    sa.Column('anh_dai_dien', sa.Text(), nullable=True),
    sa.Column('cccd', sa.String(length=12), nullable=False),
    sa.Column('gioi_tinh', sa.Boolean(), nullable=False),
    sa.Column('ngay_sinh', sa.Date(), nullable=False),
    sa.Column('que_quan', sa.String(length=255), nullable=True),
    sa.Column('sdt', sa.String(length=10), nullable=True),
    sa.Column('don_vi_cong_tac', sa.String(length=255), nullable=False),
    sa.Column('dia_chi_cong_tac', sa.Text(), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('ma_khoa', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['email'], ['TaiKhoan.email'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ma_khoa'], ['Khoa.ma_khoa'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('ma_gv'),
    sa.UniqueConstraint('cccd'),
    sa.UniqueConstraint('sdt')
    )
    op.create_table('HNCDeTaiGV',
    sa.Column('ma_hnc', sa.Integer(), nullable=False),
    sa.Column('ma_de_tai', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ma_de_tai'], ['DeTaiNCKHGV.ma_de_tai'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ma_hnc'], ['HuongNghienCuu.ma_hnc'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ma_hnc', 'ma_de_tai')
    )
    op.create_table('HNCDeTaiSV',
    sa.Column('ma_hnc', sa.Integer(), nullable=False),
    sa.Column('ma_de_tai', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ma_de_tai'], ['DeTaiNCKHSV.ma_de_tai'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ma_hnc'], ['HuongNghienCuu.ma_hnc'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ma_hnc', 'ma_de_tai')
    )
    op.create_table('HoiDongKhoa',
    sa.Column('ma_hd', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('so_hd', sa.Integer(), nullable=True),
    sa.Column('loai_hd', sa.Integer(), nullable=False),
    sa.Column('ngay_bao_cao', sa.Date(), nullable=True),
    sa.Column('dia_diem', sa.Text(), nullable=True),
    sa.Column('trang_thai', sa.Integer(), nullable=True),
    sa.Column('ma_khoa', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['ma_khoa'], ['Khoa.ma_khoa'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('ma_hd')
    )
    op.create_table('KhenThuongDeTai',
    sa.Column('ma_de_tai', sa.Integer(), nullable=False),
    sa.Column('ma_khen_thuong', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ma_de_tai'], ['DeTaiNCKHSV.ma_de_tai'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ma_khen_thuong'], ['KhenThuong.ma_khen_thuong'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ma_de_tai', 'ma_khen_thuong')
    )
    op.create_table('SinhVien',
    sa.Column('ma_sv', sa.String(length=20), nullable=False),
    sa.Column('ten_sv', sa.String(length=255), nullable=False),
    sa.Column('anh_dai_dien', sa.Text(), nullable=True),
    sa.Column('cccd', sa.String(length=12), nullable=False),
    sa.Column('gioi_tinh', sa.Boolean(), nullable=False),
    sa.Column('ngay_sinh', sa.Date(), nullable=False),
    sa.Column('que_quan', sa.String(length=255), nullable=True),
    sa.Column('sdt', sa.String(length=10), nullable=True),
    sa.Column('lop_hc', sa.String(length=15), nullable=False),
    sa.Column('khoa_hoc', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('ma_khoa', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['email'], ['TaiKhoan.email'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ma_khoa'], ['Khoa.ma_khoa'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('ma_sv'),
    sa.UniqueConstraint('cccd'),
    sa.UniqueConstraint('sdt')
    )
    op.create_table('TVHDTruong',
    sa.Column('ma_tv', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('gmail', sa.String(length=50), nullable=True),
    sa.Column('ten_tv', sa.String(length=255), nullable=False),
    sa.Column('noi_cong_tac', sa.Text(), nullable=False),
    sa.Column('tu_cach', sa.Integer(), nullable=False),
    sa.Column('ma_hd', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ma_hd'], ['HoiDongTruong.ma_hd'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ma_tv')
    )
    op.create_table('TaiLieuNCKHGV',
    sa.Column('ma_tai_lieu', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('loai_tai_lieu', sa.Integer(), nullable=False),
    sa.Column('link_tep', sa.Text(), nullable=False),
    sa.Column('thoi_gian_nop', sa.DateTime(), nullable=False),
    sa.Column('trang_thai', sa.Integer(), nullable=False),
    sa.Column('phan_hoi', sa.Text(), nullable=True),
    sa.Column('ma_de_tai', sa.Integer(), nullable=False),
    sa.Column('ma_hd', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ma_de_tai'], ['DeTaiNCKHGV.ma_de_tai'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ma_hd'], ['HoiDongTruong.ma_hd'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('ma_tai_lieu')
    )
    op.create_table('ThongBao',
    sa.Column('ma_tb', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('tieu_de', sa.String(length=255), nullable=False),
    sa.Column('noi_dung', sa.Text(), nullable=False),
    sa.Column('link_tep', sa.Text(), nullable=True),
    sa.Column('anh_dinh_kem', sa.Text(), nullable=True),
    sa.Column('thoi_gian_gui', sa.DateTime(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['email'], ['TaiKhoan.email'], ),
    sa.PrimaryKeyConstraint('ma_tb')
    )
    op.create_table('ChucDanhKhoaHoc',
    sa.Column('ma_cd', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chuc_danh', sa.String(length=255), nullable=True),
    sa.Column('chuc_vu', sa.String(length=255), nullable=True),
    sa.Column('nam_dat_pgs', sa.Integer(), nullable=True),
    sa.Column('nam_dat_gs', sa.Integer(), nullable=True),
    sa.Column('ma_gv', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['ma_gv'], ['GiangVien.ma_gv'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ma_cd')
    )
    op.create_table('DangKyNCKH',
    sa.Column('ma_dk', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ma_sv', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['ma_sv'], ['SinhVien.ma_sv'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ma_dk')
    )
    op.create_table('DeTaiKHCN',
    sa.Column('ma_dt_khcn', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ten_dt', sa.String(length=255), nullable=False),
    sa.Column('cap_quan_ly', sa.String(length=255), nullable=False),
    sa.Column('tg_thuc_hien', sa.Integer(), nullable=False),
    sa.Column('trang_thai', sa.Boolean(), nullable=False),
    sa.Column('ket_qua', sa.String(length=20), nullable=True),
    sa.Column('loai_de_tai', sa.Integer(), nullable=False),
    sa.Column('tu_cach', sa.Boolean(), nullable=True),
    sa.Column('ma_gv', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['ma_gv'], ['GiangVien.ma_gv'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ma_dt_khcn')
    )
    op.create_table('GVHNC',
    sa.Column('ma_gv', sa.String(length=20), nullable=False),
    sa.Column('ma_hnc', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ma_gv'], ['GiangVien.ma_gv'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ma_hnc'], ['HuongNghienCuu.ma_hnc'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ma_gv', 'ma_hnc')
    )
    op.create_table('GiaiThuongKHCN',
    sa.Column('ma_gt_khcn', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('noi_dung', sa.Text(), nullable=False),
    sa.Column('nam_tang_thuong', sa.Integer(), nullable=False),
    sa.Column('loai_giai_thuong', sa.Boolean(), nullable=False),
    sa.Column('ma_gv', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['ma_gv'], ['GiangVien.ma_gv'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ma_gt_khcn')
    )
    op.create_table('HoatDongCaoHoc',
    sa.Column('ma_hdch', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ten_de_tai', sa.String(length=255), nullable=False),
    sa.Column('vai_tro_hd', sa.Integer(), nullable=False),
    sa.Column('ten_nguoi_hoc', sa.String(length=255), nullable=False),
    sa.Column('co_so_dao_tao', sa.Text(), nullable=False),
    sa.Column('hoc_vi_dao_tao', sa.Integer(), nullable=False),
    sa.Column('ma_gv', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['ma_gv'], ['GiangVien.ma_gv'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ma_hdch')
    )
    op.create_table('HoatDongGiangDay',
    sa.Column('ma_hdgd', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ten_hoc_phan', sa.String(length=255), nullable=False),
    sa.Column('chuyen_nganh', sa.String(length=255), nullable=False),
    sa.Column('trinh_do', sa.Integer(), nullable=False),
    sa.Column('so_nam', sa.Integer(), nullable=False),
    sa.Column('noi_giang_day', sa.Text(), nullable=False),
    sa.Column('ma_gv', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['ma_gv'], ['GiangVien.ma_gv'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ma_hdgd')
    )
    op.create_table('HocVi',
    sa.Column('ma_hv', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hoc_vi', sa.Integer(), nullable=False),
    sa.Column('nam_dat', sa.Integer(), nullable=False),
    sa.Column('nganh', sa.String(length=255), nullable=False),
    sa.Column('chuyen_nganh', sa.Text(), nullable=False),
    sa.Column('ma_gv', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['ma_gv'], ['GiangVien.ma_gv'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ma_hv')
    )
    op.create_table('KhoaDaoTao',
    sa.Column('ma_kdt', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ten_kdt', sa.String(length=255), nullable=False),
    sa.Column('noi_dao_tao', sa.Text(), nullable=False),
    sa.Column('tg_bat_dau', sa.Date(), nullable=False),
    sa.Column('tg_ket_thuc', sa.Date(), nullable=False),
    sa.Column('van_bang_chung_chi', sa.String(length=50), nullable=False),
    sa.Column('ma_gv', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['ma_gv'], ['GiangVien.ma_gv'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ma_kdt')
    )
    op.create_table('NguoiNhanTB',
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('ma_tb', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['email'], ['TaiKhoan.email'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ma_tb'], ['ThongBao.ma_tb'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('email', 'ma_tb')
    )
    op.create_table('NhomNCKH',
    sa.Column('ma_nhom', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trang_thai', sa.Integer(), nullable=False),
    sa.Column('ma_gv', sa.String(length=20), nullable=True),
    sa.Column('ma_de_tai', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ma_de_tai'], ['DeTaiNCKHSV.ma_de_tai'], ),
    sa.ForeignKeyConstraint(['ma_gv'], ['GiangVien.ma_gv'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('ma_nhom')
    )
    op.create_table('PhatMinhSangChe',
    sa.Column('ma_pmsc', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ten_pmsc', sa.String(length=255), nullable=False),
    sa.Column('loai_pmsc', sa.String(length=255), nullable=False),
    sa.Column('thong_tin', sa.Text(), nullable=False),
    sa.Column('tg_cap_bang', sa.Integer(), nullable=False),
    sa.Column('ma_gv', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['ma_gv'], ['GiangVien.ma_gv'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ma_pmsc')
    )
    op.create_table('QuaTrinhCongTac',
    sa.Column('ma_ct', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nam_bat_dau', sa.Integer(), nullable=False),
    sa.Column('nam_ket_thuc', sa.Integer(), nullable=False),
    sa.Column('vi_tri', sa.String(length=255), nullable=False),
    sa.Column('linh_vuc', sa.String(length=255), nullable=False),
    sa.Column('co_quan', sa.Text(), nullable=False),
    sa.Column('ma_gv', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['ma_gv'], ['GiangVien.ma_gv'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ma_ct')
    )
    op.create_table('SachBaoCongBo',
    sa.Column('ma_sach', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ten_sach', sa.String(length=255), nullable=False),
    sa.Column('vi_tri', sa.Boolean(), nullable=False),
    sa.Column('noi_xb', sa.Text(), nullable=False),
    sa.Column('nam_xb', sa.Integer(), nullable=False),
    sa.Column('loai_sach', sa.Integer(), nullable=False),
    sa.Column('ma_gv', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['ma_gv'], ['GiangVien.ma_gv'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ma_sach')
    )
    op.create_table('TVHDKhoa',
    sa.Column('ma_hd', sa.Integer(), nullable=False),
    sa.Column('ma_gv', sa.String(length=20), nullable=False),
    sa.Column('tu_cach', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ma_gv'], ['GiangVien.ma_gv'], ),
    sa.ForeignKeyConstraint(['ma_hd'], ['HoiDongKhoa.ma_hd'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ma_hd', 'ma_gv')
    )
    op.create_table('TaiLieuNCKHSV',
    sa.Column('ma_tai_lieu', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('loai_tai_lieu', sa.Integer(), nullable=False),
    sa.Column('link_tep', sa.Text(), nullable=True),
    sa.Column('thoi_gian_nop', sa.DateTime(), nullable=True),
    sa.Column('trang_thai', sa.Integer(), nullable=False),
    sa.Column('phan_hoi', sa.Text(), nullable=True),
    sa.Column('ma_hd_khoa', sa.Integer(), nullable=True),
    sa.Column('ma_hd_truong', sa.Integer(), nullable=True),
    sa.Column('ma_de_tai', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ma_de_tai'], ['DeTaiNCKHSV.ma_de_tai'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ma_hd_khoa'], ['HoiDongKhoa.ma_hd'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ma_hd_truong'], ['HoiDongTruong.ma_hd'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('ma_tai_lieu')
    )
    op.create_table('ThanhVienNCKHGV',
    sa.Column('ma_de_tai', sa.Integer(), nullable=False),
    sa.Column('ma_gv', sa.String(length=20), nullable=False),
    sa.Column('vi_tri_tham_gia', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ma_de_tai'], ['DeTaiNCKHGV.ma_de_tai'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ma_gv'], ['GiangVien.ma_gv'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ma_de_tai', 'ma_gv')
    )
    op.create_table('TrinhDoHocVan',
    sa.Column('ma_tdhv', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bac_dao_tao', sa.Integer(), nullable=False),
    sa.Column('chuyen_nganh', sa.String(length=255), nullable=False),
    sa.Column('noi_dao_tao', sa.Text(), nullable=False),
    sa.Column('nam_tot_nghiep', sa.Integer(), nullable=False),
    sa.Column('ma_gv', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['ma_gv'], ['GiangVien.ma_gv'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ma_tdhv')
    )
    op.create_table('TrinhDoNgoaiNgu',
    sa.Column('ma_nn', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ngoai_ngu', sa.String(length=50), nullable=False),
    sa.Column('nghe', sa.Integer(), nullable=True),
    sa.Column('noi', sa.Integer(), nullable=True),
    sa.Column('doc', sa.Integer(), nullable=True),
    sa.Column('viet', sa.Integer(), nullable=True),
    sa.Column('ma_gv', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['ma_gv'], ['GiangVien.ma_gv'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ma_nn')
    )
    op.create_table('HNCDangKyNCKH',
    sa.Column('ma_hnc', sa.Integer(), nullable=False),
    sa.Column('ma_dk', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ma_dk'], ['DangKyNCKH.ma_dk'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ma_hnc'], ['HuongNghienCuu.ma_hnc'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ma_hnc', 'ma_dk')
    )
    op.create_table('NguyenVongDK',
    sa.Column('ma_dk', sa.Integer(), nullable=False),
    sa.Column('ma_gv', sa.String(length=20), nullable=False),
    sa.Column('muc_uu_tien', sa.Integer(), nullable=False),
    sa.Column('trang_thai', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ma_dk'], ['DangKyNCKH.ma_dk'], ),
    sa.ForeignKeyConstraint(['ma_gv'], ['GiangVien.ma_gv'], ),
    sa.PrimaryKeyConstraint('ma_dk', 'ma_gv')
    )
    op.create_table('ThanhVienNhomSV',
    sa.Column('ma_nhom', sa.Integer(), nullable=False),
    sa.Column('ma_sv', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['ma_nhom'], ['NhomNCKH.ma_nhom'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['ma_sv'], ['SinhVien.ma_sv'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('ma_nhom', 'ma_sv')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ThanhVienNhomSV')
    op.drop_table('NguyenVongDK')
    op.drop_table('HNCDangKyNCKH')
    op.drop_table('TrinhDoNgoaiNgu')
    op.drop_table('TrinhDoHocVan')
    op.drop_table('ThanhVienNCKHGV')
    op.drop_table('TaiLieuNCKHSV')
    op.drop_table('TVHDKhoa')
    op.drop_table('SachBaoCongBo')
    op.drop_table('QuaTrinhCongTac')
    op.drop_table('PhatMinhSangChe')
    op.drop_table('NhomNCKH')
    op.drop_table('NguoiNhanTB')
    op.drop_table('KhoaDaoTao')
    op.drop_table('HocVi')
    op.drop_table('HoatDongGiangDay')
    op.drop_table('HoatDongCaoHoc')
    op.drop_table('GiaiThuongKHCN')
    op.drop_table('GVHNC')
    op.drop_table('DeTaiKHCN')
    op.drop_table('DangKyNCKH')
    op.drop_table('ChucDanhKhoaHoc')
    op.drop_table('ThongBao')
    op.drop_table('TaiLieuNCKHGV')
    op.drop_table('TVHDTruong')
    op.drop_table('SinhVien')
    op.drop_table('KhenThuongDeTai')
    op.drop_table('HoiDongKhoa')
    op.drop_table('HNCDeTaiSV')
    op.drop_table('HNCDeTaiGV')
    op.drop_table('GiangVien')
    op.drop_table('TaiKhoan')
    op.drop_table('Khoa')
    op.drop_table('KhenThuong')
    op.drop_table('HuongNghienCuu')
    op.drop_table('HoiDongTruong')
    op.drop_table('DeTaiNCKHSV')
    op.drop_table('DeTaiNCKHGV')
    # ### end Alembic commands ###
