#List Hướng Nghiên Cứu
huong_nghien_cuu_list = [
    "Trí tuệ nhân tạo và Máy học",
    "Xử lý ngôn ngữ tự nhiên",
    "Mạng và An ninh thông tin",
    "Hệ thống nhúng và IoT",
    "Thị giác máy tính và Xử lý ảnh",
    "Khoa học dữ liệu và Big Data",
    "Điện tử công suất và Điều khiển tự động",
    "Quản lý tài chính và Ngân hàng số",
    "Kinh tế số và Blockchain",
    "Công nghệ sinh học thực phẩm",
    "Du lịch thông minh và Quản trị du lịch",
    "Ngôn ngữ học ứng dụng",
    "Pháp luật số và Trí tuệ nhân tạo trong luật",
    "Vật liệu tiên tiến và Nano",
    "Công nghệ sinh học Y dược",
    "Hệ thống thông tin và Khoa học dữ liệu",
    "Mạng viễn thông và Điện toán đám mây",
    "Kỹ thuật Robot và Tự động hóa",
    "Tâm lý học và Giáo dục học",
    "Kinh doanh số và Marketing số",
    "An toàn thông tin và Bảo mật dữ liệu",
    "Công nghệ môi trường và Biến đổi khí hậu",
    "Năng lượng tái tạo và Kỹ thuật môi trường",
    "Quản trị chuỗi cung ứng và Logistics"
]

# Dictionary Khoa
khoa_dict = [
    {"ma_khoa": "K01", "ten_khoa": "Khoa Đào tạo Cơ bản", "dia_chi": "Nhà B101 Nguyễn Hiền, quận Hai Bà Trưng, TP .Hà Nội"},
    {"ma_khoa": "K02", "ten_khoa": "Khoa Tạo dáng công nghiệp", "dia_chi": "Số 422 Vĩnh Hưng, quận Hoàng Mai, TP. Hà Nội"},
    {"ma_khoa": "K03", "ten_khoa": "Khoa Kinh tế", "dia_chi": "Số 193 Vĩnh Hưng, quận Hoàng Mai, TP. Hà Nội"},
    {"ma_khoa": "K04", "ten_khoa": "Khoa Tài chính Ngân hàng", "dia_chi": "Số 422 Vĩnh Hưng, quận Hoàng Mai, TP. Hà Nội"},
    {"ma_khoa": "K05", "ten_khoa": "Khoa Luật", "dia_chi": "Số 193 Vĩnh Hưng, quận Hoàng Mai, TP. Hà Nội"},
    {"ma_khoa": "K06", "ten_khoa": "Viện Công nghệ Sinh học & Công nghệ thực phẩm", "dia_chi": "Tòa nhà C, số 301 Nguyễn Trãi, quận Thanh Xuân, TP. Hà Nội"},
    {"ma_khoa": "K07", "ten_khoa": "Khoa Công nghệ Thông tin", "dia_chi": "Số 96 Định Công, quận Hoàng Mai, TP. Hà Nội"},
    {"ma_khoa": "K08", "ten_khoa": "Khoa Điện - Điện tử", "dia_chi": "Số 422 Vĩnh Hưng, quận Hoàng Mai, TP. Hà Nội"},
    {"ma_khoa": "K09", "ten_khoa": "Khoa Du lịch", "dia_chi": "Số 301 Nguyễn Trãi, quận Thanh Xuân, TP. Hà Nội"},
    {"ma_khoa": "K10", "ten_khoa": "Khoa Tiếng Anh", "dia_chi": "Số 301 Nguyễn Trãi, quận Thanh Xuân, TP. Hà Nội"},
    {"ma_khoa": "K11", "ten_khoa": "Khoa Tiếng Trung Quốc", "dia_chi": "Số 193 Vĩnh Hưng, quận Hoàng Mai, TP. Hà Nội"},
    {"ma_khoa": "K12", "ten_khoa": "Khoa Đào tạo Từ xa", "dia_chi": "Nhà B101 Nguyễn Hiền, quận Hai Bà Trưng, TP .Hà Nội"},
    {"ma_khoa": "K13", "ten_khoa": "Trung tâm Đào tạo Trực tuyến", "dia_chi": "Nhà B101 Nguyễn Hiền, quận Hai Bà Trưng, TP .Hà Nội"},
    {"ma_khoa": "K14", "ten_khoa": "Trung tâm Đại học Mở Hà Nội tại Đà Nẵng", "dia_chi": "Số 295 Nguyễn Tất Thành, Thanh Bình, Hải Châu, Đà Nẵng"},
    {"ma_khoa": "K15", "ten_khoa": "Trung tâm Giáo dục Thể chất & Quốc phòng An ninh", "dia_chi": "Lại Ốc, Văn Giang, Hưng Yên"},
]

#List Tên
ho_list = ["Nguyễn", "Trần", "Lê", "Phạm", "Hoàng", "Huỳnh", "Phan", "Vũ", "Đặng", "Bùi", "Đỗ", "Hồ", "Võ", "Trương", "Ngô", "Dương", "Đinh", "Trịnh", "Lý", "Tạ", "Tăng", "Tô", "Tống", "Nghiêm", "Bạch", "Chu", "Từ", "Lương", "Khuất", "Quách", "Ôn", "Cao", "Hà", "Khương", "La", "Mạc", "Ngọ"
]
ten_dem_list = [  "Văn", "Hữu", "Đình", "Ngọc", "Minh", "Quốc", "Thị", "Thu", "Mai", "Thanh", "Anh", "Quang", "Xuân", "Tiến", "Hương", "Đức", "Nhật", "Thái", "Khắc", "Hoàng", "Trọng", "Công", "Phúc", "Đan", "Bảo", "Hải", "Hiếu", "Kim", "Vĩnh", "Duy"]
ten_list = [ "Hạnh", "Ánh", "Nam", "Hải", "Dũng", "Hương", "Linh", "Lan", "Tùng", "Trang", "Bình", "Khánh", "Phương", "Hà", "Sơn", "Tuấn", "Vân", "Hiền", "Thảo", "Thanh", "Quang", "Trung", "Hậu", "Thịnh", "Giang", "Diễm", "Ngọc", "Mai", "Hải Yến", "Minh", "Long", "Đức", "Tâm", "Hồng", "Đạt", "Kiên", "Tiến", "Tú", "Phong", "Huy", "Hoàng", "Việt", "Nga", "Xuân", "Nhung", "Trà", "Duy", "Cường", "Châu"]

#Dictionary CCCD
# Danh sách tỉnh thành và mã căn cước công dân
cccd_3sodau = {
    "Hà Nội": "001",
    "Hồ Chí Minh": "079",
    "Hải Phòng": "031",
    "Đà Nẵng": "048",
    "Cần Thơ": "092",
    "An Giang": "089",
    "Bà Rịa - Vũng Tàu": "077",
    "Bắc Giang": "240",
    "Bắc Kạn": "281",
    "Bạc Liêu": "260",
    "Bắc Ninh": "222",
    "Bến Tre": "272",
    "Bình Định": "264",
    "Bình Dương": "248",
    "Bình Phước": "244",
    "Bình Thuận": "250",
    "Cà Mau": "270",
    "Cao Bằng": "280",
    "Đắk Lắk": "266",
    "Đắk Nông": "267",
    "Điện Biên": "282",
    "Đồng Nai": "245",
    "Đồng Tháp": "258",
    "Gia Lai": "268",
    "Hà Giang": "290",
    "Hà Nam": "226",
    "Hà Tĩnh": "228",
    "Hải Dương": "225",
    "Hậu Giang": "093",
    "Hòa Bình": "289",
    "Hưng Yên": "221",
    "Khánh Hòa": "272",
    "Kiên Giang": "294",
    "Kon Tum": "269",
    "Lai Châu": "283",
    "Lâm Đồng": "269",
    "Lạng Sơn": "288",
    "Lào Cai": "285",
    "Long An": "296",
    "Nam Định": "228",
    "Nghệ An": "246",
    "Ninh Bình": "229",
    "Ninh Thuận": "251",
    "Phú Thọ": "227",
    "Phú Yên": "273",
    "Quảng Bình": "211",
    "Quảng Nam": "213",
    "Quảng Ngãi": "215",
    "Quảng Ninh": "205",
    "Quảng Trị": "212",
    "Sóc Trăng": "256",
    "Sơn La": "284",
    "Tây Ninh": "243",
    "Thái Bình": "223",
    "Thái Nguyên": "228",
    "Thanh Hóa": "247",
    "Thừa Thiên Huế": "218",
    "Tiền Giang": "256",
    "Trà Vinh": "258",
    "Tuyên Quang": "287",
    "Vĩnh Long": "259",
    "Vĩnh Phúc": "211",
    "Yên Bái": "286"
}