"""Initial migration

Revision ID: 7d5638b12ba0
Revises: 
Create Date: 2025-03-02 15:08:44.232730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d5638b12ba0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('DeTaiNCKHGV',
    sa.Column('ma_de_tai', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ten_de_tai', sa.String(length=255), nullable=False),
    sa.Column('thoi_gian_bat_dau', sa.Date(), nullable=False),
    sa.Column('thoi_han_nghiem_thu', sa.Date(), nullable=False),
    sa.Column('thoi_gian_thuc_nghiem', sa.Date(), nullable=True),
    sa.Column('trang_thai', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('ma_de_tai')
    )
    op.create_table('HuongNghienCuu',
    sa.Column('ma_huong_nc', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ten_huong_nc', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('ma_huong_nc')
    )
    op.create_table('Khoa',
    sa.Column('ma_khoa', sa.String(length=20), nullable=False),
    sa.Column('ten_khoa', sa.String(length=255), nullable=False),
    sa.Column('dia_chi', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('ma_khoa')
    )
    op.create_table('TaiKhoan',
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('mat_khau', sa.String(length=255), nullable=False),
    sa.Column('quyen_han', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('email')
    )
    op.create_table('DeTaiNCKHSV',
    sa.Column('ma_de_tai', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ten_de_tai', sa.String(length=255), nullable=False),
    sa.Column('thuong_cap_khoa', sa.String(length=255), nullable=True),
    sa.Column('thuong_cap_truong', sa.String(length=255), nullable=True),
    sa.Column('dot_thuc_hien', sa.Integer(), nullable=False),
    sa.Column('trang_thai', sa.Integer(), nullable=False),
    sa.Column('ma_khoa', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['ma_khoa'], ['Khoa.ma_khoa'], ),
    sa.PrimaryKeyConstraint('ma_de_tai')
    )
    op.create_table('GiangVien',
    sa.Column('ma_gv', sa.String(length=20), nullable=False),
    sa.Column('ten_gv', sa.String(length=100), nullable=False),
    sa.Column('cccd', sa.String(length=12), nullable=False),
    sa.Column('gioi_tinh', sa.Boolean(), nullable=False),
    sa.Column('ngay_sinh', sa.Date(), nullable=False),
    sa.Column('que_quan', sa.String(length=255), nullable=True),
    sa.Column('sdt', sa.Integer(), nullable=True),
    sa.Column('don_vi_cong_tac', sa.String(length=255), nullable=True),
    sa.Column('dia_chi_cong_tac', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('ma_khoa', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['email'], ['TaiKhoan.email'], ),
    sa.ForeignKeyConstraint(['ma_khoa'], ['Khoa.ma_khoa'], ),
    sa.PrimaryKeyConstraint('ma_gv'),
    sa.UniqueConstraint('cccd'),
    sa.UniqueConstraint('sdt')
    )
    op.create_table('HuongNghienCuuDeTaiGV',
    sa.Column('ma_huong_nc', sa.Integer(), nullable=False),
    sa.Column('ma_de_tai', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ma_de_tai'], ['DeTaiNCKHGV.ma_de_tai'], ),
    sa.ForeignKeyConstraint(['ma_huong_nc'], ['HuongNghienCuu.ma_huong_nc'], ),
    sa.PrimaryKeyConstraint('ma_huong_nc', 'ma_de_tai')
    )
    op.create_table('SinhVien',
    sa.Column('ma_sv', sa.String(length=20), nullable=False),
    sa.Column('ten_sv', sa.String(length=100), nullable=False),
    sa.Column('cccd', sa.String(length=12), nullable=False),
    sa.Column('gioi_tinh', sa.Boolean(), nullable=False),
    sa.Column('ngay_sinh', sa.Date(), nullable=False),
    sa.Column('que_quan', sa.String(length=255), nullable=True),
    sa.Column('sdt', sa.Integer(), nullable=True),
    sa.Column('lop_hanh_chinh', sa.String(length=15), nullable=False),
    sa.Column('khoa_hoc', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('ma_khoa', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['email'], ['TaiKhoan.email'], ),
    sa.ForeignKeyConstraint(['ma_khoa'], ['Khoa.ma_khoa'], ),
    sa.PrimaryKeyConstraint('ma_sv'),
    sa.UniqueConstraint('cccd'),
    sa.UniqueConstraint('sdt')
    )
    op.create_table('TaiLieuNCKHGV',
    sa.Column('ma_tai_lieu', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('loai_tai_lieu', sa.Integer(), nullable=False),
    sa.Column('tep_tai_lieu', sa.String(length=255), nullable=False),
    sa.Column('thoi_gian_nop', sa.DateTime(), nullable=False),
    sa.Column('trang_thai', sa.Integer(), nullable=False),
    sa.Column('phan_hoi', sa.String(length=255), nullable=True),
    sa.Column('ma_de_tai', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ma_de_tai'], ['DeTaiNCKHGV.ma_de_tai'], ),
    sa.PrimaryKeyConstraint('ma_tai_lieu')
    )
    op.create_table('ChucDanhKhoaHoc',
    sa.Column('ma_cdkh', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chuc_danh', sa.String(length=255), nullable=False),
    sa.Column('chuc_vu', sa.String(length=255), nullable=True),
    sa.Column('nam_pgs', sa.Integer(), nullable=True),
    sa.Column('nam_gs', sa.Integer(), nullable=True),
    sa.Column('ma_gv', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['ma_gv'], ['GiangVien.ma_gv'], ),
    sa.PrimaryKeyConstraint('ma_cdkh')
    )
    op.create_table('DangKyNCKH',
    sa.Column('ma_dk', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ma_sv', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['ma_sv'], ['SinhVien.ma_sv'], ),
    sa.PrimaryKeyConstraint('ma_dk')
    )
    op.create_table('DeTaiKHCN',
    sa.Column('ma_sp', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ten_sp', sa.String(length=255), nullable=False),
    sa.Column('cap_co_quan_ql', sa.String(length=255), nullable=True),
    sa.Column('thoi_gian_thuc_hien', sa.String(length=255), nullable=True),
    sa.Column('trang_thai', sa.Integer(), nullable=True),
    sa.Column('ket_qua', sa.Integer(), nullable=True),
    sa.Column('loai_de_tai', sa.Integer(), nullable=True),
    sa.Column('ma_gv', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['ma_gv'], ['GiangVien.ma_gv'], ),
    sa.PrimaryKeyConstraint('ma_sp')
    )
    op.create_table('GVHuongNghienCuu',
    sa.Column('ma_gv', sa.String(length=20), nullable=False),
    sa.Column('ma_huong_nc', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ma_gv'], ['GiangVien.ma_gv'], ),
    sa.ForeignKeyConstraint(['ma_huong_nc'], ['HuongNghienCuu.ma_huong_nc'], ),
    sa.PrimaryKeyConstraint('ma_gv', 'ma_huong_nc')
    )
    op.create_table('GiaiThuongKHCN',
    sa.Column('ma_giai_thuong', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('noi_dung', sa.String(length=255), nullable=False),
    sa.Column('nam_tang_thuong', sa.Integer(), nullable=True),
    sa.Column('loai_giai_thuong', sa.Boolean(), nullable=False),
    sa.Column('ma_gv', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['ma_gv'], ['GiangVien.ma_gv'], ),
    sa.PrimaryKeyConstraint('ma_giai_thuong')
    )
    op.create_table('HoatDongCaoHoc',
    sa.Column('ma_hdch', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ten_de_tai', sa.String(length=100), nullable=False),
    sa.Column('vai_tro_huong_dan', sa.Integer(), nullable=False),
    sa.Column('ten_nguoi_hoc', sa.String(length=100), nullable=False),
    sa.Column('co_so_dao_tao', sa.String(length=255), nullable=False),
    sa.Column('hoc_vi', sa.Integer(), nullable=False),
    sa.Column('ma_gv', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['ma_gv'], ['GiangVien.ma_gv'], ),
    sa.PrimaryKeyConstraint('ma_hdch')
    )
    op.create_table('HoatDongGiangDay',
    sa.Column('ma_hoat_dong', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ten_hoc_phan', sa.String(length=100), nullable=False),
    sa.Column('chuyen_nganh', sa.String(length=255), nullable=False),
    sa.Column('trinh_do', sa.Integer(), nullable=False),
    sa.Column('so_nam', sa.Integer(), nullable=False),
    sa.Column('noi_day', sa.String(length=255), nullable=False),
    sa.Column('ma_gv', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['ma_gv'], ['GiangVien.ma_gv'], ),
    sa.PrimaryKeyConstraint('ma_hoat_dong')
    )
    op.create_table('HocVi',
    sa.Column('ma_hoc_vi', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hoc_vi', sa.Integer(), nullable=False),
    sa.Column('nam_dat', sa.Integer(), nullable=False),
    sa.Column('nganh', sa.String(length=255), nullable=False),
    sa.Column('chuyen_nganh', sa.String(length=255), nullable=True),
    sa.Column('ma_gv', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['ma_gv'], ['GiangVien.ma_gv'], ),
    sa.PrimaryKeyConstraint('ma_hoc_vi')
    )
    op.create_table('HuongNghienCuuDeTaiSV',
    sa.Column('ma_huong_nc', sa.Integer(), nullable=False),
    sa.Column('ma_de_tai', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ma_de_tai'], ['DeTaiNCKHSV.ma_de_tai'], ),
    sa.ForeignKeyConstraint(['ma_huong_nc'], ['HuongNghienCuu.ma_huong_nc'], ),
    sa.PrimaryKeyConstraint('ma_huong_nc', 'ma_de_tai')
    )
    op.create_table('KhoaDaoTao',
    sa.Column('ma_khoa_dao_tao', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ten_khoa', sa.String(length=100), nullable=False),
    sa.Column('noi_dao_tao', sa.String(length=255), nullable=False),
    sa.Column('thoi_gian_dao_tao', sa.String(length=255), nullable=False),
    sa.Column('chung_chi', sa.Integer(), nullable=False),
    sa.Column('ma_gv', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['ma_gv'], ['GiangVien.ma_gv'], ),
    sa.PrimaryKeyConstraint('ma_khoa_dao_tao')
    )
    op.create_table('NhomNCKH',
    sa.Column('ma_nhom', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('trang_thai', sa.Integer(), nullable=False),
    sa.Column('ma_de_tai', sa.Integer(), nullable=False),
    sa.Column('ma_gv', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['ma_de_tai'], ['DeTaiNCKHSV.ma_de_tai'], ),
    sa.ForeignKeyConstraint(['ma_gv'], ['GiangVien.ma_gv'], ),
    sa.PrimaryKeyConstraint('ma_nhom')
    )
    op.create_table('PhatMinhSangChe',
    sa.Column('ma_pmsc', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ten_pmsc', sa.String(length=100), nullable=False),
    sa.Column('loai_phat_minh', sa.String(length=10), nullable=False),
    sa.Column('thong_tin', sa.String(length=255), nullable=False),
    sa.Column('thoi_gian', sa.Date(), nullable=False),
    sa.Column('ma_gv', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['ma_gv'], ['GiangVien.ma_gv'], ),
    sa.PrimaryKeyConstraint('ma_pmsc')
    )
    op.create_table('QuaTrinhCongTac',
    sa.Column('ma_qtct', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('thoi_gian', sa.String(length=255), nullable=False),
    sa.Column('vi_tri_cong_tac', sa.String(length=255), nullable=False),
    sa.Column('linh_vuc_chuyen_mon', sa.String(length=255), nullable=False),
    sa.Column('co_quan_cong_tac', sa.String(length=255), nullable=False),
    sa.Column('ma_gv', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['ma_gv'], ['GiangVien.ma_gv'], ),
    sa.PrimaryKeyConstraint('ma_qtct')
    )
    op.create_table('SachBaoCongNghe',
    sa.Column('ma_sach', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ten_sach', sa.String(length=100), nullable=False),
    sa.Column('vi_tri', sa.Boolean(), nullable=False),
    sa.Column('noi_xuat_ban', sa.String(length=255), nullable=False),
    sa.Column('nam_xuat_ban', sa.Integer(), nullable=False),
    sa.Column('loai_sach', sa.Integer(), nullable=False),
    sa.Column('ma_gv', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['ma_gv'], ['GiangVien.ma_gv'], ),
    sa.PrimaryKeyConstraint('ma_sach')
    )
    op.create_table('TaiLieuNCKHSV',
    sa.Column('ma_tai_lieu', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('loai_tai_lieu', sa.Integer(), nullable=False),
    sa.Column('tep_tai_lieu', sa.String(length=255), nullable=False),
    sa.Column('thoi_gian_nop', sa.DateTime(), nullable=False),
    sa.Column('trang_thai', sa.Integer(), nullable=False),
    sa.Column('phan_hoi', sa.String(length=255), nullable=True),
    sa.Column('ma_de_tai', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ma_de_tai'], ['DeTaiNCKHSV.ma_de_tai'], ),
    sa.PrimaryKeyConstraint('ma_tai_lieu')
    )
    op.create_table('ThanhVienDeTaiNCKHGV',
    sa.Column('ma_de_tai', sa.Integer(), nullable=False),
    sa.Column('ma_gv', sa.String(length=20), nullable=False),
    sa.Column('vi_tri_tham_du', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ma_de_tai'], ['DeTaiNCKHGV.ma_de_tai'], ),
    sa.ForeignKeyConstraint(['ma_gv'], ['GiangVien.ma_gv'], ),
    sa.PrimaryKeyConstraint('ma_de_tai', 'ma_gv')
    )
    op.create_table('TrinhDoHocVan',
    sa.Column('ma_tdhv', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bac_dao_tao', sa.Integer(), nullable=False),
    sa.Column('chuyen_nganh', sa.String(length=255), nullable=False),
    sa.Column('noi_dao_tao', sa.String(length=255), nullable=False),
    sa.Column('nam_tot_nghiep', sa.Integer(), nullable=False),
    sa.Column('ma_gv', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['ma_gv'], ['GiangVien.ma_gv'], ),
    sa.PrimaryKeyConstraint('ma_tdhv')
    )
    op.create_table('TrinhDoNgoaiNgu',
    sa.Column('ma_nn', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ngoai_ngu', sa.String(length=100), nullable=False),
    sa.Column('nghe', sa.Integer(), nullable=False),
    sa.Column('noi', sa.Integer(), nullable=False),
    sa.Column('doc', sa.Integer(), nullable=False),
    sa.Column('viet', sa.Integer(), nullable=False),
    sa.Column('ma_gv', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['ma_gv'], ['GiangVien.ma_gv'], ),
    sa.PrimaryKeyConstraint('ma_nn')
    )
    op.create_table('HuongNghienCuuDangKyNCKH',
    sa.Column('ma_dk', sa.Integer(), nullable=False),
    sa.Column('ma_huong_nc', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ma_dk'], ['DangKyNCKH.ma_dk'], ),
    sa.ForeignKeyConstraint(['ma_huong_nc'], ['HuongNghienCuu.ma_huong_nc'], ),
    sa.PrimaryKeyConstraint('ma_dk', 'ma_huong_nc')
    )
    op.create_table('NguyenVongDangKyNCKH',
    sa.Column('ma_dk', sa.Integer(), nullable=False),
    sa.Column('ma_gv', sa.String(length=20), nullable=False),
    sa.Column('muc_uu_tien', sa.Integer(), nullable=False),
    sa.Column('trang_thai', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ma_dk'], ['DangKyNCKH.ma_dk'], ),
    sa.ForeignKeyConstraint(['ma_gv'], ['GiangVien.ma_gv'], ),
    sa.PrimaryKeyConstraint('ma_dk', 'ma_gv')
    )
    op.create_table('ThanhVienNhomNCKH',
    sa.Column('ma_nhom', sa.Integer(), nullable=False),
    sa.Column('ma_sv', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['ma_nhom'], ['NhomNCKH.ma_nhom'], ),
    sa.ForeignKeyConstraint(['ma_sv'], ['SinhVien.ma_sv'], ),
    sa.PrimaryKeyConstraint('ma_nhom', 'ma_sv')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ThanhVienNhomNCKH')
    op.drop_table('NguyenVongDangKyNCKH')
    op.drop_table('HuongNghienCuuDangKyNCKH')
    op.drop_table('TrinhDoNgoaiNgu')
    op.drop_table('TrinhDoHocVan')
    op.drop_table('ThanhVienDeTaiNCKHGV')
    op.drop_table('TaiLieuNCKHSV')
    op.drop_table('SachBaoCongNghe')
    op.drop_table('QuaTrinhCongTac')
    op.drop_table('PhatMinhSangChe')
    op.drop_table('NhomNCKH')
    op.drop_table('KhoaDaoTao')
    op.drop_table('HuongNghienCuuDeTaiSV')
    op.drop_table('HocVi')
    op.drop_table('HoatDongGiangDay')
    op.drop_table('HoatDongCaoHoc')
    op.drop_table('GiaiThuongKHCN')
    op.drop_table('GVHuongNghienCuu')
    op.drop_table('DeTaiKHCN')
    op.drop_table('DangKyNCKH')
    op.drop_table('ChucDanhKhoaHoc')
    op.drop_table('TaiLieuNCKHGV')
    op.drop_table('SinhVien')
    op.drop_table('HuongNghienCuuDeTaiGV')
    op.drop_table('GiangVien')
    op.drop_table('DeTaiNCKHSV')
    op.drop_table('TaiKhoan')
    op.drop_table('Khoa')
    op.drop_table('HuongNghienCuu')
    op.drop_table('DeTaiNCKHGV')
    # ### end Alembic commands ###
